#!/bin/bash 
cd mysql 
docker build -t menna/mysql . 
cd ../nginx 
docker build -t menna/nginx . 
cd ../phpfpm 
docker build -t menna/phpfpm . 
cd ../wp 
docker build -t menna/wp . 
cd ..
docker run -d --name mysql menna/mysql 
docker run -it --name wp menna/wp
docker run -d --name app --volumes-from wp --link mysql:db menna/phpfpm 
docker run -d -p 80:80 --name nginx --volumes-from wp --link app:app menna/nginx 
